version: "3.8"
services:
  filen-webdav:
    container_name: filen-webdav
    image: filen/cli:latest
    command: >
      --email ${FILEN_MAIL}
      --password ${FILEN_PASSWORD}
      webdav
      --w-user admin
      --w-password ${WEBDAV_PASSWORD}

    networks:
      - restic-network

  backrest:
    image: garethgeorge/backrest:latest
    container_name: backrest
    hostname: backrest
    volumes:
      - ./backrest/data:/data
      - ./backrest/config:/config     # Change this to a persistant storage or volume!
      - ./backrest/cache:/cache
      - ./rclone:/root/.config/rclone # rclone config - refer to README.md for details
      # - /userdata:/userdata # [optional] mount local paths to backup here.
    environment:
      - BACKREST_DATA=/mnt/user/appdata/backrest/data # path for backrest data. restic binary and the database are placed here.
      - BACKREST_CONFIG=/config/config.json # path for the backrest config file.
      - XDG_CACHE_HOME=/cache # path for the restic cache which greatly improves performance.
      - TZ=Berlin/Germany # set the timezone for the container, used as the timezone for cron jobs.
    restart: unless-stopped
    ports:
      - 9898:9898
    networks:
      - restic-network

networks:
  restic-network: